### PR TITLE
Do not use_inline_resources in nrpe_check provider

### PR DESCRIPTION
**Pull request by Annih**
Hello,

Following  #51 , the `nrpe_check` provider is failing to reload the `service[nrpe]`
> Chef::Exceptions::ResourceNotFound: nrpe_check[check] (nrpe-criteo::default line 31) had an error: Chef::Exceptions::ResourceNotFound: resource file[/etc/nagios/nrpe.d/check.cfg] is configured to notify resource service[nrpe] with action reload, but service[nrpe] cannot be found in the resource collection. file[/etc/nagios/nrpe.d/check.cfg] is defined in /var/chef/cache/cookbooks/nrpe/providers/check.rb:48:in `block in class_from_file'

This is due to the addition of the `use_inline_resources` [in the provider](https://github.com/schubergphilis/nrpe/pull/51/commits/f00967d63424da52ba7bf5ed0ba7d8fb2fdacc6e#diff-84e022ae391d3d3ae346d6686a1d922aR20); as re-explained by @coderanger here https://github.com/chef/chef/issues/4410, the use_inline_resources isolate the provider from the global resource collection.

Cc: @aboten

### CODE REVIEW

**Comment by Annih** [comment]
Tests are flacky ... and I can't relaunch them without amending my commit.

**Comment by jvanlieshout** [comment]
Hi @Annih, removing `use_inline_resources` would not fix the issue for chef 12.5 - 12.9.38. Here you can read about the resources behavior in providers: http://serverfault.com/questions/729013/chef-12-5-custom-resources-accessing-resources-in-recipes
Please have a look it my PR: #56 
I'm currently trying to find someone willing to merge 😉

**Comment by snkutlu** [comment]
Hi @Annih

I think this is solved with PR #56 If you agree, I can close this..

**Comment by snkutlu** [comment]
Fixed by #56

**Pull request closed without merging**
