### PR TITLE
Fixed URL for source installation

### PR DESCRIPTION
**Pull request by jolcese**
Soruceforge has changed the download URL

### CODE REVIEW

**Comment by jolcese** [comment]
Ok, thanks.
Now I'm handling split major and minor versions.

**Comment by tas50** [comment]
Major / minor is going to break anyone that previously set this attribute.  They'll end up with the current version instead.  I think the best thing is probably just to make it a complete URL string and do away with the URL building nonsense.  It would be a breaking change, but it would simplify things a lot

**Comment by glensc** [comment]
May i just suggest to use this url:

    http://downloads.sourceforge.net/nagios/nrpe-2.15.tar.gz

it's simple and has worked well for last, eee 5 years?

**Comment by tas50** [comment]
I'm inclined to just do away with the magic and use a single URL.  It would be a breaking change, but it makes a lot more sense.

**Comment by sbotman** [comment]
:+1: for making this just a simple complete URL to the package.

**Comment by glensc** [comment]
well, have you considered that you still need directory name where to `chdir` after unpack?
how you're going to obtain that?

what if someone uses git export url from github? then the subdir could be `nrpe-nrpe-cd137874147184787888111`

**Comment by 5c077yP** [comment]
:+1: for the complete URL attribute 
@glensc what's about parsing the filename out of the URL like: http://stackoverflow.com/a/13706970

**Comment by tas50** [comment]
The current URL has been tested and is working in the cookbook right now. I'm going to close this out.

**Pull request closed without merging**
